# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01-ping.yaml
- name: ping
  hosts: web
  tasks:
    - name: Pinging to 54.210.75.105
      ansible.builtin.ping:
