# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 011-when.yaml
- name: when
  hosts: web
  become: yes
  tasks:
    - name: "Print details of expense user"
      ansible.builtin.command: id expense
      ignore_errors: true # Intentional errors
      register: ID_EXPENSE_OUTPUT
    - name: "Read id expense output"
      ansible.builtin.debug:
        msg: "{{ID_EXPENSE_OUTPUT}}"
    - name: "Create expense user if not exists"
      ansible.builtin.command: useradd expense
      when: ID_EXPENSE_OUTPUT.rc != 0 # rc works similar to exit status, 0 => success, 1 => failure

