# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 012-using-filters.yaml
- name: Using filters to convert string to integer
  hosts: web
  vars_prompt:
    name: INPUT_STRING
    prompt: "Enter any number"
    private: no
  tasks:
    - name: "Convert prompt string to integer and compare"
      ansible.builtin.debug:
        msg: "Number {{INPUT_STRING}} is greater than 10"
      when: INPUT_STRING | int > 10 # incorrect strings as converted to 0
    - name: "Convert prompt string to integer and compare"
      ansible.builtin.debug:
        msg: "Number {{INPUT_STRING}} is less than or equal to 10"
      when: INPUT_STRING | int <= 10 # incorrect strings as converted to 0

- name: Using filters to provide default text
  hosts: web
  tasks:
    - name: "Provide default text"
      ansible.builtin.debug:
        msg: "Courses: {{courses | default('No courses available')}}"

- name: Using filters to convert text to different case
  hosts: web
  vars:
    USERNAME: Harsha Vardhan
  tasks:
    - name: "Convert text to uppercase"
      ansible.builtin.debug:
        msg: "Name: {{USERNAME | upper}}"
    - name: "Convert text to lowercase"
      ansible.builtin.debug:
        msg: "Name: {{USERNAME | lower}}"

- name: Using filters to get unique elements of a list
  hosts: web
  vars:
    numbers: [1, 2, 2, 3, 4, 5, 5, 5, 2, 2]
  tasks:
    - name: "Extract list of unique elements from a list"
      ansible.builtin.debug:
        msg: "Unique Elements: {{numbers | unique}}"

- name: Using filters to get maximum and minimum of a list
  hosts: web
  vars:
    numbers: [1, 2, 2, 3, 4, 5, 5, 5, 2, 2]
  tasks:
    - name: "Extract maximum and minimum from a list"
      ansible.builtin.debug:
        msg: "Maximum element: {{numbers | max}}, Minimum element: {{numbers | min}}"

- name: Using filters to convert dictionary to items (List of key-values)
  hosts: web
  vars:
    details:
      trainer: Siva Kumar
      course: DevOps in Telugu
      duration: 120
  tasks:
    - name: "Convert dictionary to items"
      ansible.builtin.debug:
        msg: "Items: {{details | dict2items}}"
