# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 013-loop.yaml
- name: Using loop to install packages
  hosts: web
  become: yes
  tasks:
    - name: "Install multiple packages"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - mysql
        - nodejs
        - nginx

- name: Using loop to install and remove packages
  hosts: web
  become: yes
  tasks:
    - name: "Install multiple packages"
      ansible.builtin.dnf:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: mysql, state: installed }
        - { name: nodejs, state: absent }
        - { name: nginx, state: absent }
