# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02-nginx.yaml
- name: Install and Run Nginx
  become: yes
  hosts: web
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
