- name: Install and Run Nginx
  become: yes
  hosts: web
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
