- name: Play One
  hosts: localhost
  tasks:
    - name: Play One and Task One
      ansible.builtin.debug:
        msg: "Hello from Play One and Task One"
    - name: Play One and Task Two
      ansible.builtin.debug:
        msg: "Hello from Play One and Task Two"

- name: Play Two
  hosts: localhost
  tasks:
    - name: Play Two and Task One
      ansible.builtin.debug:
        msg: "Hello from Play One and Task One"
    - name: Play Two and Task Two
      ansible.builtin.debug:
        msg: "Hello from Play Two and Task Two"
