- name: vars
  hosts: web
  vars:
    trainer: Siva Kumar
    course: DevOps
    duration: 120
  tasks:
    - name: Variables using vars
      ansible.builtin.debug:
        msg: "We are learning {{course}} from {{trainer}} of {{duration}} hours"
