# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 07-vars-from-inventory.yaml
- name: vars-from-inventory
  hosts: web
  # NO MENTION NEEDED
  tasks:
    - name: Variables from inventory
      ansible.builtin.debug:
        msg: "We are learning {{course}} from {{trainer}} of {{duration}} hours"
##########################

# inventory.ini PREVIEW #

# [web]
# 54.210.75.105

# [web:vars]
# course="DevOps in Telugu"
# trainer="Siva Kumar"
# duration=120

##########################
